version: '2'
services:
  db:
    image: postgres:9
    env_file:
      - ./env
  web:
    build: ..
    depends_on:
      - db
    env_file:
      - ./env
    ports:
      - "8080:8080"
      - "8081:8081"
