#!/bin/sh

{{ bindir }}/serial-vault-admin database --config={{ confdir }}/settings.yaml
#TODO It is needed to modify serial-vault params to be set in same way as admin tool.
#That would set coherence in both services using -- or - for long and short params.
{{ bindir }}/serial-vault -config={{ confdir }}/settings.yaml
